### ISSUE TITLE
All pendulum affiliated tokens (pendulum.pw) have disappeared from stellar exchanges 

### ISSUE THREAD

**Issue by IvicosJones** [pendulum-chain/substrate-stellar-sdk#3]
All Pendulum.pw tokens have disappeared from stellar exchanges such as Lobstr, and there haven't been any updates, info, or information given to the pendulum community regarding their investments. each pendulum token is valued at less than .00000001 xlm, and now you all as a company look very scammy.

**Comment by TorstenStueber** [comment]
@IvicosJones Thank you for letting us know about it.
In June we [posted](https://twitter.com/pendulum_chain/status/1406992561995190275) a warning saying that projects named "Pendulum" publicly announcing a token are not affiliated with us. This includes the project mentioned.
We also recently added a disclaimer to our [website](https://pendulumchain.org/).

You will find official information about Pendulum on our website and the channels linked to from there. You will also find a link to our discord where you can contact us. Please use our GitHub only in relation to our open source projects.
